version: '3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Root1234
      - MSSQL_PID=Express
    ports: 
      - "1433:1433"
  csharptgbot:
    image: tg-bot
    build:
      context: .
      dockerfile: DockerfileDev
    restart: on-failure
    depends_on:
      - sqlserver
